CONTIKI_PROJECT = ledAlarm

all: $(CONTIKI_PROJECT)

CONTIKI = /home/user/contiki

#CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

APPS += er-coap
APPS += rest-engine

include $(CONTIKI)/Makefile.include