CONTIKI_PROJECT = sens-temp

all: $(CONTIKI_PROJECT)

CONTIKI = /home/user/contiki

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

APPS += er-coap
APPS += rest-engine

include $(CONTIKI)/Makefile.include

